// <auto-generated />
using System;
using BetApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BetApp.Api.Migrations
{
    [DbContext(typeof(BetAppContext))]
    partial class BetAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BetApp.Api.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("balance");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_username");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("BetApp.Api.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("author");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int?>("SportCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_category_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_article");

                    b.HasIndex("SportCategoryId")
                        .HasDatabaseName("ix_article_sport_category_id");

                    b.ToTable("article", (string)null);
                });

            modelBuilder.Entity("BetApp.Api.Models.Bonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.Property<decimal>("Value")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_bonus");

                    b.ToTable("bonus", (string)null);
                });

            modelBuilder.Entity("BetApp.Api.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BonusId")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_id");

                    b.Property<DateTime>("PlacedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("PotentialPayout")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("potential_payout");

                    b.Property<decimal>("Stake")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("stake");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalOdds")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("total_odds");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_coupon");

                    b.HasIndex("BonusId")
                        .HasDatabaseName("ix_coupon_bonus_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_coupon_user_id");

                    b.ToTable("coupon", (string)null);
                });

            modelBuilder.Entity("BetApp.Api.Models.CouponSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CouponId")
                        .HasColumnType("integer")
                        .HasColumnName("coupon_id");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("market");

                    b.Property<decimal>("Odds")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("odds");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result");

                    b.Property<string>("Selection")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("selection");

                    b.HasKey("Id")
                        .HasName("pk_coupon_selection");

                    b.HasIndex("CouponId")
                        .HasDatabaseName("ix_coupon_selection_coupon_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_coupon_selection_event_id");

                    b.ToTable("coupon_selection", (string)null);
                });

            modelBuilder.Entity("BetApp.Api.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Result")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("result");

                    b.Property<int>("SportCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_category_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_event");

                    b.HasIndex("SportCategoryId")
                        .HasDatabaseName("ix_event_sport_category_id");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("ix_event_start_time");

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("BetApp.Api.Models.EventParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<string>("Side")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("side");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_event_participant");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_event_participant_event_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_event_participant_player_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_event_participant_team_id");

                    b.ToTable("event_participant", (string)null);
                });

            modelBuilder.Entity("BetApp.Api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("nationality");

                    b.Property<string>("Position")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("position");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_player");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_player_team_id");

                    b.ToTable("player", (string)null);
                });

            modelBuilder.Entity("BetApp.Api.Models.SportCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sport_category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_sport_category_name");

                    b.ToTable("sport_category", (string)null);
                });

            modelBuilder.Entity("BetApp.Api.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("country");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SportCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_category_id");

                    b.HasKey("Id")
                        .HasName("pk_team");

                    b.HasIndex("SportCategoryId")
                        .HasDatabaseName("ix_team_sport_category_id");

                    b.ToTable("team", (string)null);
                });

            modelBuilder.Entity("BetApp.Api.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Method")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_transaction");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_transaction_user_id");

                    b.ToTable("transaction", (string)null);
                });

            modelBuilder.Entity("BetApp.Api.Models.Article", b =>
                {
                    b.HasOne("BetApp.Api.Models.SportCategory", "SportCategory")
                        .WithMany()
                        .HasForeignKey("SportCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_article_sport_categories_sport_category_id");

                    b.Navigation("SportCategory");
                });

            modelBuilder.Entity("BetApp.Api.Models.Coupon", b =>
                {
                    b.HasOne("BetApp.Api.Models.Bonus", "Bonus")
                        .WithMany("Coupons")
                        .HasForeignKey("BonusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_coupon_bonus_bonus_id");

                    b.HasOne("BetApp.Api.Models.AppUser", "User")
                        .WithMany("Coupons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coupon_app_user_user_id");

                    b.Navigation("Bonus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetApp.Api.Models.CouponSelection", b =>
                {
                    b.HasOne("BetApp.Api.Models.Coupon", "Coupon")
                        .WithMany("Selections")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coupon_selection_coupon_coupon_id");

                    b.HasOne("BetApp.Api.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coupon_selection_events_event_id");

                    b.Navigation("Coupon");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("BetApp.Api.Models.Event", b =>
                {
                    b.HasOne("BetApp.Api.Models.SportCategory", "SportCategory")
                        .WithMany()
                        .HasForeignKey("SportCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_sport_categories_sport_category_id");

                    b.Navigation("SportCategory");
                });

            modelBuilder.Entity("BetApp.Api.Models.EventParticipant", b =>
                {
                    b.HasOne("BetApp.Api.Models.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_participant_event_event_id");

                    b.HasOne("BetApp.Api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_event_participant_players_player_id");

                    b.HasOne("BetApp.Api.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_event_participant_teams_team_id");

                    b.Navigation("Event");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BetApp.Api.Models.Player", b =>
                {
                    b.HasOne("BetApp.Api.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_player_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BetApp.Api.Models.Team", b =>
                {
                    b.HasOne("BetApp.Api.Models.SportCategory", "SportCategory")
                        .WithMany()
                        .HasForeignKey("SportCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_sport_category_sport_category_id");

                    b.Navigation("SportCategory");
                });

            modelBuilder.Entity("BetApp.Api.Models.Transaction", b =>
                {
                    b.HasOne("BetApp.Api.Models.AppUser", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_app_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetApp.Api.Models.AppUser", b =>
                {
                    b.Navigation("Coupons");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BetApp.Api.Models.Bonus", b =>
                {
                    b.Navigation("Coupons");
                });

            modelBuilder.Entity("BetApp.Api.Models.Coupon", b =>
                {
                    b.Navigation("Selections");
                });

            modelBuilder.Entity("BetApp.Api.Models.Event", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("BetApp.Api.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
